CREATE PROC DOANHTHU_THEONV
    @IDNV NCHAR(10) = NULL
AS
BEGIN
    SELECT 
        ROW_NUMBER() OVER (ORDER BY SUM(CTHDB.SOLUONG * CTHDB.DONGIA) DESC) AS STT,
        NV.IDNV,
        NV.HOTEN AS TENNHANVIEN,
        SUM(CTHDB.SOLUONG * CTHDB.DONGIA) AS DOANHTHU
    FROM HOADONBAN HDB
    JOIN CHITIETHDB CTHDB ON HDB.IDHDB = CTHDB.IDHDB
    JOIN NHANVIEN NV ON HDB.IDNV = NV.IDNV
    WHERE (@IDNV IS NULL OR NV.IDNV = @IDNV)
    GROUP BY NV.IDNV, NV.HOTEN
    ORDER BY DOANHTHU DESC
END
