CREATE PROC DOANHTHU_THEOSP
    @IDSP NCHAR(10) = NULL
AS
BEGIN
    SELECT 
        ROW_NUMBER() OVER (ORDER BY SUM(CTHDB.SOLUONG * CTHDB.DONGIA) DESC) AS STT,
        SP.IDSP,
        SP.TENSP,
        SUM(CTHDB.SOLUONG) AS TONGSOLUONG,
        SUM(CTHDB.SOLUONG * CTHDB.DONGIA) AS DOANHTHU
    FROM HOADONBAN HDB
    JOIN CHITIETHDB CTHDB ON HDB.IDHDB = CTHDB.IDHDB
    JOIN SANPHAM SP ON CTHDB.IDSP = SP.IDSP
    WHERE (@IDSP IS NULL OR SP.IDSP = @IDSP)
    GROUP BY SP.IDSP, SP.TENSP
    ORDER BY DOANHTHU DESC
END
