CREATE PROC DOANHTHU_THEODM
    @IDDM NCHAR(10) = NULL
AS
BEGIN
    SELECT 
        ROW_NUMBER() OVER (ORDER BY SUM(CTHDB.SOLUONG * CTHDB.DONGIA) DESC) AS STT,
        DM.IDDM,
        DM.TENDM,
        SUM(CTHDB.SOLUONG * CTHDB.DONGIA) AS DOANHTHU
    FROM HOADONBAN HDB
    JOIN CHITIETHDB CTHDB ON HDB.IDHDB = CTHDB.IDHDB
    JOIN SANPHAM SP ON CTHDB.IDSP = SP.IDSP
    JOIN DANHMUCSP DM ON SP.IDDM = DM.IDDM
    WHERE (@IDDM IS NULL OR DM.IDDM = @IDDM)
    GROUP BY DM.IDDM, DM.TENDM
    ORDER BY DOANHTHU DESC
END
