CREATE PROCEDURE DOANHTHU_THEONGAY
    @TUNGAY DATE,
    @DENNGAY DATE
AS
BEGIN
    SELECT 
        ROW_NUMBER() OVER (ORDER BY HDB.IDHDB) AS STT,
        HDB.IDHDB,
        NV.HOTEN AS TENNHANVIEN,
        KH.HOTEN AS TENKHACHHANG,
        SP.IDSP AS MASP,
        SP.TENSP,
        SZ.TENSIZE,
        M.TENMAU,
        CT.SOLUONG,
        CT.DONGIA,
        HDB.GIAMGIA,
        (CT.SOLUONG * CT.DONGIA - ISNULL(HDB.GIAMGIA, 0)) AS TONGTIEN,
        HDB.NGAYLAP
    FROM HOADONBAN HDB
    JOIN NHANVIEN NV ON HDB.IDNV = NV.IDNV
    JOIN KHACHHANG KH ON HDB.IDKH = KH.IDKH
    JOIN CHITIETHDB CT ON HDB.IDHDB = CT.IDHDB
    JOIN SANPHAM SP ON CT.IDSP = SP.IDSP
    JOIN SIZE SZ ON CT.IDSIZE = SZ.IDSIZE
    JOIN MAU M ON CT.IDMAU = M.IDMAU
    WHERE HDB.NGAYLAP BETWEEN @TUNGAY AND @DENNGAY
END
