CREATE PROCEDURE HOADONBAN_KH
    @IDKH NCHAR(10) = NULL
AS
BEGIN
    SELECT 
        ROW_NUMBER() OVER (ORDER BY HDB.NGAYLAP DESC) AS STT,
        HDB.IDHDB,
        HDB.NGAYLAP,
        KH.IDKH,
        KH.HOTEN AS TENKHACHHANG,
        SP.IDSP,
        SP.TENSP,
        SZ.TENSIZE,
        M.TENMAU,
	CTHDB.SOLUONG,
        CTHDB.DONGIA,
	HDB.TONGTIEN
    FROM HOADONBAN HDB
    JOIN KHACHHANG KH ON HDB.IDKH = KH.IDKH
    JOIN CHITIETHDB CTHDB ON HDB.IDHDB = CTHDB.IDHDB
    JOIN SANPHAM SP ON CTHDB.IDSP = SP.IDSP
    LEFT JOIN SIZE SZ ON CTHDB.IDSIZE = SZ.IDSIZE
    LEFT JOIN MAU M ON CTHDB.IDMAU = M.IDMAU
    WHERE (@IDKH IS NULL OR KH.IDKH = @IDKH)
    ORDER BY HDB.NGAYLAP DESC, HDB.IDHDB
END
