CREATE PROC LOINHUAN_THEONGAY
    @TUNGAY DATE,
    @DENNGAY DATE
AS
BEGIN
    SELECT
        ROW_NUMBER() OVER (ORDER BY HDB.NGAYLAP) AS STT,
        HDB.NGAYLAP,
        SUM(CT.SOLUONG) AS TONGSOLUONG,
        SUM(CT.SOLUONG * CT.DONGIA) AS DOANHTHU,
        SUM(CT.SOLUONG * SP.DGNHAP) AS TONGCHI,
        SUM((CT.SOLUONG * CT.DONGIA) - (CT.SOLUONG * SP.DGNHAP)) - 
            SUM(ISNULL(HDB.GIAMGIA, 0)) AS LOINHUAN
    FROM HOADONBAN HDB
    JOIN CHITIETHDB CT ON HDB.IDHDB = CT.IDHDB
    JOIN SANPHAM SP ON CT.IDSP = SP.IDSP
    WHERE HDB.NGAYLAP BETWEEN @TUNGAY AND @DENNGAY
    GROUP BY HDB.NGAYLAP
    ORDER BY HDB.NGAYLAP
END
