CREATE PROC LOINHUAN_THEOSP
    @IDSP NCHAR(10) = NULL
AS
BEGIN
    SELECT 
        ROW_NUMBER() OVER (ORDER BY SUM((CT.DONGIA - SP.DGNHAP) * CT.SOLUONG) DESC) AS STT,
        SP.IDSP,
        SP.TENSP,
        SUM(CT.SOLUONG) AS TONGSOLUONG,
        SUM(CT.SOLUONG * CT.DONGIA) AS DOANHTHU,
        SUM(SP.DGNHAP * CT.SOLUONG) AS TONGCHI,
        SUM((CT.DONGIA - SP.DGNHAP) * CT.SOLUONG) AS LOINHUAN
    FROM CHITIETHDB CT
    JOIN HOADONBAN HDB ON CT.IDHDB = HDB.IDHDB
    JOIN SANPHAM SP ON CT.IDSP = SP.IDSP
    WHERE (@IDSP IS NULL OR SP.IDSP = @IDSP)
    GROUP BY SP.IDSP, SP.TENSP
    ORDER BY LOINHUAN DESC
END
