CREATE PROCEDURE BC_NHAPHANG
    @TuNgay DATE = NULL,
    @DenNgay DATE = NULL
AS
BEGIN
    SELECT 
        ROW_NUMBER() OVER (ORDER BY NCC.TENNCC, HDN.NGAYLAP) AS STT,
        NCC.TENNCC AS NCC,
        HDN.NGAYLAP AS NGAYNHAP,
        SP.TENSP AS TENSP,
        CTHDN.SOLUONG AS SL,
        CTHDN.DONGIA AS DGNHAP,
        (CTHDN.SOLUONG * CTHDN.DONGIA) AS THANHTIEN
    FROM 
        HOADONNHAP HDN
    INNER JOIN NHACUNGCAP NCC ON HDN.IDNCC = NCC.IDNCC
    INNER JOIN CHITIETHDN CTHDN ON HDN.IDHDN = CTHDN.IDHDN
    INNER JOIN SANPHAM SP ON CTHDN.IDSP = SP.IDSP
    WHERE HDN.NGAYLAP BETWEEN @TuNgay AND @DenNgay
    ORDER BY NCC.TENNCC, HDN.NGAYLAP
END
